apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::332563595315:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-K3CUZLRCLYW8
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::332563595315:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-08-16T10:41:20Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1313"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 9daeea19-ec26-4f52-a948-18c8b0b7f46d
